dataset: MNIST
device: [0]

ipc: 50
syn_steps: 80
expert_epochs: 3
zca: False
lr_img: 1000
lr_teacher: 0.01
buffer_path: ../buffer_storage/
data_path: ../dataset
ema_decay: 0.9995
Iteration: 100
batch_syn: 100

# wandb
project: MNIST_ipc50

num_eval: 1
eval_it: 10
skip_first_eva: False

lr_y: 2.
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
expansion_end_epoch: 2000
batch_train: 128
min_start_epoch: 0
current_max_start_epoch: 2
max_start_epoch: 4
lr_lr: 0.00001
zca: True

depth_ratio: 0.25
loss_ratio: 0.25
